<?php
echo "<!DOCTYPE html>\n";
echo "<html>\n";
echo "<head>\n";
echo "<meta charset=\"UTF-8\">\n";
echo "<link rel=\"stylesheet\" href=\"style.css\">\n";
echo "<link rel=\"stylesheet\" href=\"font.css\">\n";
echo "<title>Webbiplob.com</title>\n";
echo "<script type=\"text/javascript\">\n";
echo "var timer;\n";
echo "function scrolltop()\n";
echo "{\n";
echo "document.getElementById('scrollmenu').style.top=document.body.scrollTop;\n";
echo "timer=setTimeout(\"scrolltop()\",1);\n";
echo "}\n";
echo "function stoptimer()\n";
echo "{\n";
echo "clearTimeout(timer);\n";
echo "}\n";
echo "</script\n";
echo "</head>\n";
echo "\n";
echo "<body>\n";
echo "<div id=\"main\">\n";
echo "\n";
echo "<div id=\"banner\">\n";
echo "<body onload=\"scrolltop()\" onunload=\"stoptimer()\">\n";
echo "<span id=\"scrollmenu\" style=\"position:absolute\">\n";
echo "<b>Menu</b><br />\n";
echo "<a href=\"https://webbiplob.com\">ওয়েব বিপ্লব</a><br />\n";
echo "<a href=\".\">প্রাথমিক ও গণশিক্ষা</a><br />\n";
echo "<a href=\"../../www.altavista.com/default.htm\">Altavista</a><br />\n";
echo "</span>\n";
echo "\n";
echo "<center><img src=\"photo/m.jpg\" alt=\"Paris\" width=\"300\" height=\"90\">\n";
echo "<h1>ভাংবাড়ীয়া সরকারী প্রাথমিক বিদ্যালয়।<img src=\"photo/school (2).jpg\" height=\"40\" width=\"45\"></center></h1></font color>\n";
echo "\n";
echo "</div>\n";
echo "<script type=\"text/javascript\">\n";
echo "function moveleft()\n";
echo "{\n";
echo "document.getElementById('header').style.position=\"absolute\";\n";
echo "document.getElementById('header').style.left=\"0\";\n";
echo "}\n";
echo "\n";
echo "function moveback()\n";
echo "{\n";
echo "document.getElementById('header').style.position=\"relative\";\n";
echo "}\n";
echo "</script>\n";
echo "\n";
echo "<div id=\"menu\">\n";
echo "<h4 id=\"header\" \n";
echo "\n";
echo "onmouseover=\"moveleft()\"\n";
echo "onmouseout=\"moveback()\">\n";
echo "\n";
echo "<ul>\n";
echo "<li> <a href=\"#\">নীড় পাতা</a>\n";
echo "<li> <a href=\"#\">ইতিহাস</a>\n";
echo "<li> <a href=\"#\">এসএমসি</a>\n";
echo "<li> <a href=\"#\">পিটিএ</a>\n";
echo "<li> <a href=\"#\">কাব স্কাউটিং</a>\n";
echo "<li> <a href=\"#\">ছাত্র সভা</a>\n";
echo "<li> <a href=\"#\">মালামাল বহি</a>\n";
echo "<li> <a href=\"#\">উপবৃত্তি</a>\n";
echo "<li> <a href=\"#\">চাকা ও শাশি</a>\n";
echo "</h4>\n";
echo "</ul>\n";
echo "</div>\n";
echo "<div id=\"maincontent\">\n";
echo "<div id=\"sidebar\">\n";
echo "<ul>\n";
echo "<li> <a href=\"#\">নীড় পাতা</a>\n";
echo "<li> <a href=\"head.html\">প্রধান শিক্ষকের বাণী</a>\n";
echo "<li> <a href=\"#\">আমাদের শিক্ষকগণ</a>\n";
echo "<li> <a href=\"#\">আমাদের ছাত্রগণ</a>\n";
echo "<li> <a href=\"#\">গ্রন্থাগার</a>\n";
echo "<li> <a href=\"#\">পরীক্ষার ফল</a>\n";
echo "<li> <a href=\"#\">পরীক্ষার রুটিন</a>\n";
echo "<li> <a href=\"#\">সিলেবাস</a>\n";
echo "<li> <a href=\"#\">আমাদের পাঠ্যসূচি</a>\n";
echo "<li> <a href=\"#\">সহ শিক্ষা</a>\n";
echo "\n";
echo "</ul></div>\n";
echo "<div id=\"maincontent\">\n";
echo "<div id=\"sidebar2\">\n";
echo "<ul>\n";
echo "<li> <a href=\"#\">হলদে পাখির দল।</a>\n";
echo "<li> <a href=\"#\">জমা জমির খাজনা</a>\n";
echo "<li> <a href=\"#\"> মেরামত</a>\n";
echo "<li> <a href=\"#\"> সিলিভ কমিটি</a>\n";
echo "<li> <a href=\"#\"> সিলিভ পরীকল্পনা</a>\n";
echo "<li> <a href=\"#\"> ক্ষুদে ডাক্তারের দল</a>\n";
echo "<li> <a href=\"#\"> সততা স্টোর</a>\n";
echo "<li> <a href=\"#\"> শিক্ষা উপকরণ</a>\n";
echo "<li> <a href=\"#\"> শিশু জরিপ</a>\n";
echo "<li> <a href=\"#\"> ক্যাচমেন্টের ম্যাপ</a>\n";
echo "</div>\n";
echo "<div id =\"content\">\n";
echo "<marquee><font color=\"red\">২০০০ সালের ছাত্র/ছাত্রী ভর্তি চলছে।</marquee></font color>\n";
echo "<center><h2> ভাংবাড়ীয়া সরকারী প্রাথমিক বিদ্যালয়।<img src=\"photo/giphy1.gif\"></h2>\n";
echo "\n";
echo "                    </p>\n";
echo "<div class=\"dropdown\">\n";
echo "  <img src=\"photo/m.jpg\" alt=\"Bhangbaria\" width=\"100\" height=\"50\">\n";
echo "  <div class=\"dropdown-content\">\n";
echo "  <img src=\"photo/m.jpg\" alt=\"Cinque Terre\" width=\"300\" height=\"200\">\n";
echo "  <div class=\"desc\">Bhangbaria</div>\n";
echo "  </div>\n";
echo "</div>\n";
echo "<p>\n";
echo "বাংলাদেশের জাতীয় সংগীত। রবীন্দ্রনাথ ঠাকুর।<br>\n";
echo "আমার সোনার বাংলা, আমি তোমায় ভালোবাসি ।<br/>\n";
echo "চিরদিন তোমার আকাশ, তোমার বাতাস, আমার প্রাণে বাজায় বাঁশি ॥<br/><br/>\n";
echo "\n";
echo "ও মা, ফাগুনে তোর আমের বনে ঘ্রাণে পাগল করে,<br/>\n";
echo "মরি হায়, হায় রে—<br/>\n";
echo "ও মা, অঘ্রানে তোর ভরা ক্ষেতে আমি কী দেখেছি মধুর হাসি ॥<br/><br/>\n";
echo "\n";
echo "কী শোভা, কী ছায়া গো, কী স্নেহ, কী মায়া গো—<br/>\n";
echo "কী আঁচল বিছায়েছ বটের মূলে, নদীর কূলে কূলে ।<br/>\n";
echo "মা, তোর মুখের বাণী আমার কানে লাগে সুধার মতো,<br/>\n";
echo "মরি হায়, হায় রে—\n";
echo "</p>\n";
echo "</div>\n";
echo "<div id =\"footer\">\n";
echo "&copy MD. Mustafijur Rahman, All right reserved, 2019.</div>\n";
?>